name: neumorphic_cv
description: A new Flutter project that generates Neumorphic CV with Pure Flutter code.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  url_strategy: ^0.2.0
  flutter_neumorphic:
    git: https://github.com/jinosh05/Flutter-Neumorphic

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.4

flutter_native_splash:
  color: "#111111"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/roboto/Roboto-Black.ttf
          weight: 900
    - family: Gilda
      fonts:
        - asset: fonts/gilda/GildaDisplay-Regular.ttf
